### ISSUE TITLE
Build failure with Debian Unstable

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/eom#101]
Building with gtk3 in Debian Unstable updated as of August 29 with these build options:
--with-gtk=3.0 --prefix=/usr  --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode
make errors out with:

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcairo.so: undefined reference to symbol 'XUnlockDisplay'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:761: recipe for target 'eom' failed

I did some digging, XunlockDisplay is only found in cut-n-paste/totem-screensaver/totem-scrsaver.c

and libcairo.so is from a package that has not updated since May 13. I've build EOM many times since then-and this build failure also occurred with an earlier version of the EOM source than the 8-31-2015 GIT master snapshot I first tried today. I suspect something to do either with the GCC 5 transition or possibly the version of X I am using from an Ubuntu PPA.  If I could find a way to build EOM without the screensaver functions (which I don't need), I could finish this build.

**Comment by monsta** [comment]
Why do you think it's an upstream issue?

**Comment by infirit** [comment]
same problem as https://github.com/mate-desktop/eom/issues/94

It looks to me a problem with cairo's pkg-config..

**Comment by lukefromdc** [comment]
What I meant was that the issue is in Debian Unstable somewhere, not 
in MATE. Is there a way to simply disable all the screensaver functions from
the build so this can complete? I don't use a screensaver at all.

**Comment by lukefromdc** [comment]
The same screensavercode is found in Atril, yet that build completes. Clearly then there is a workaround for this, as it builds in one package and not another. I don't know enough about working with makefiles to find it though

**Comment by infirit** [comment]
>libcairo.so: undefined reference to symbol 'XUnlockDisplay'

If you look at the error you see that ``XunlockDisplay`` is undifined in ``libcairo.so`` and the missing symbol can be found in ``Xlib.h``. Regardless the error message is way too little info, only the full build log with ``--disable-silent-rules`` will provide enough info to look at this further.

**Comment by lukefromdc** [comment]
WORKAROUND: eom will build with --without-dbus in the build options. Found that out by manually editing first makefiles, then source to remove the offending code. It turned out the key piece was behind an #ifdef switch for dbus, so after building and running that hacked version I started new with another copy of the source and these build options:

 --with-gtk=3.0 --prefix=/usr  --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode --without-dbus

Builds and works fine, as long as you don't need any dbus screensaver functions.

**Comment by lukefromdc** [comment]
I just found that building with --disable-dbus fixes this and allows me to build EOM.
I ran another build with --disable-silent-rules, the resulting text was more than
the terminal could store and no saved build log file was made, but I was able
to cut and paste what should be the relevant code from the terminal and 
save it. It's all the screensaver stuff and is attached.  That build did not complete,
but it's only job was to provide this log.

On 9/1/2015 at 3:00 PM, "Sander Sweers" <notifications@github.com> wrote:
>
>>libcairo.so: undefined reference to symbol 'XUnlockDisplay'
>
>If you look at the error you see that ``XunlockDisplay`` is 
>undifined in ``libcairo.so`` and the missing symbol can be found 
>in ``Xlib.h``. Regardless the error message is way too little 
>info, only the full build log with ``--disable-silent-rules`` will 
>provide enough info to look at this further.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mate-desktop/eom/issues/101#issuecomment-
>136829161

/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../cut-n-paste/toolbar-editor -I../cut-n-paste/totem-screensaver -pthread -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_42 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_44 -pthread -I/usr/include/dconf -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/libexif -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/mate-desktop-2.0  -DEOM_DATA_DIR=\""/usr/share/eom"\" -DEOM_LOCALE_DIR=\""/usr/share/locale"\" -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2   -o eom eom-main.o libeom.la -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgthread-2.0 -pthread -lmate-desktop-2 -lstartup-notification-1 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lexif -ldbus-glib-1 -ldbus-1 -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo  -ljpeg ../cut-n-paste/toolbar-editor/libtoolbareditor.la ../cut-n-paste/totem-screensaver/libtotemscrsaver.la ../jpegutils/libeom-jpegutils.la -lgirepository-1.0 -lgobject-2.0 -lglib-2.0  -lm -lz 
libtool: link: gcc -I../cut-n-paste/toolbar-editor -I../cut-n-paste/totem-screensaver -pthread -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_42 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_44 -pthread -I/usr/include/dconf -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/libexif -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/mate-desktop-2.0 -DEOM_DATA_DIR=\"/usr/share/eom\" -DEOM_LOCALE_DIR=\"/usr/share/locale\" -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -o eom eom-main.o -Wl,--export-dynamic -pthread -pthread  ./.libs/libeom.a -lX11 -lXrandr -ldconf -lgmodule-2.0 -lgthread-2.0 /usr/lib/libmate-desktop-2.so -lstartup-notification-1 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lexif -ldbus-glib-1 -ldbus-1 -lrsvg-2 -lgio-2.0 -lgdk_pixbuf-2.0 -lcairo -ljpeg ../cut-n-paste/toolbar-editor/.libs/libtoolbareditor.a -lxml2 ../cut-n-paste/totem-screensaver/.libs/libtotemscrsaver.a ../jpegutils/.libs/libeom-jpegutils.a -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lm -lz -pthread
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcairo.so: undefined reference to symbol 'XUnlockDisplay'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:761: recipe for target 'eom' failed
make[3]: *** [eom] Error 1
make[3]: Leaving directory '/home/luke/Desktop/eom-master/src'
Makefile:663: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/luke/Desktop/eom-master/src'
Makefile:544: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/luke/Desktop/eom-master'
Makefile:476: recipe for target 'all' failed

**Comment by monsta** [comment]
> It looks to me a problem with cairo's pkg-config

Hmm, but in my Debian Testing VMs (one has GTK+2 build of MATE and other has GTK+3 one) all is fine.
Version of cairo is the same as in Unstable repos, 1.14.2-2.

**Comment by monsta** [comment]
> possibly the version of X I am using from an Ubuntu PPA

Well, since you're using Unstable, I think you already know that using PPAs in Debian isn't recommended. :smile:
I'd try again with the stock version - just to make sure it's not what causes the issue.

**Comment by lukefromdc** [comment]
Switching that back and forth would be a major nuisance, enough to force
use of a dedicated test partition. I don't use the screensaver and this is not
one of my forks, so for my purposes it is enough to disable dbus support in
the image viewer.

Some Ubuntu PPA's work in Debian, some don't. They may work some of the
time and not others. When they don't, when none exist, or when I need a 
different build or  a hacked package that's when I build locally. Otherwise I
would be building kernel, X, and Mesa locally too and probably better off on
Gentoo-but that would be a scratch reinstall while it was possible to convert an
old Ubuntu rolling setup to Debian Unstable in response to the upcoming
"snappy" mess.

**Comment by lukefromdc** [comment]
This seems to be fixed as of Sep 6, not sure if it was changes in Debian Unstable over the weekend or the many changes in git master since I had the build failure, but no problems now. Just build with dbus enabled.  Nobody else has reported this and it's gone now here, so closing this.
