### ISSUE TITLE
add support for webp file

### ISSUE THREAD

**Issue by hanaokaiwa** [mate-desktop/eom#104]
Eye of Mate does not support webp file on my fedora 22.
Here is what I installed.
$ rpm -q eom
eom-1.10.3-1.fc22.x86_64

But if I display "Image Collection" bar, I can see thumb of some of the webp images.
Please add support for webp files so I ccould use Eye of Mate only to view images.

**Comment by infirit** [comment]
So eom, like eog, does not handle the imageg directly and relies on gdk-pixbuf loaders. There is a bug open with the webp ppl here, https://code.google.com/p/webp/issues/detail?id=227. When that is fixed eom will automatically be able to load webp files.

**Comment by pirate486743186** [comment]
an update on this?

**Comment by baryluk** [comment]
Still not working.

I suppose the newer tracking bug was https://gitlab.gnome.org/GNOME/gdk-pixbuf/issues/103

but it also got closed because 'libwebp' library doesn't support pixbuf. Which is quite ridiculous to expect from the image decoding library. It is not a job of any image decoding library to support pixbuf.

There is some off the tree loader to do that: https://github.com/aruiz/webp-pixbuf-loader/blob/master/io-webp.c , which is the correct approach, and it does work.  The security concerns should be handled via sandboxing and seccomp.

**Comment by Ygarr** [comment]
EOM 1.24.1 still no support

**Comment by rbuj** [comment]
This feature was added on EOM 2.24, but you need to install the package webp-pixbuf-loader, for instance on Fedora:
```shell
$ sudo dnf install -y webp-pixbuf-loader
$ rpm -qi webp-pixbuf-loader
Name        : webp-pixbuf-loader
Version     : 0.0.1
Release     : 9.20191003gitfb04954.fc32
Architecture: x86_64
Install Date: diumenge, 20 de setembre de 2020, 12:19:44
Group       : Unspecified
Size        : 46746
License     : LGPLv2+
Signature   : RSA/SHA256, divendres, 31 de gener de 2020, 23:35:07, Key ID 6c13026d12c944d0
Source RPM  : webp-pixbuf-loader-0.0.1-9.20191003gitfb04954.fc32.src.rpm
Build Date  : divendres, 31 de gener de 2020, 07:17:54
Build Host  : buildvm-09.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/aruiz/webp-pixbuf-loader
Bug URL     : https://bugz.fedoraproject.org/webp-pixbuf-loader
Summary     : WebP image loader for GTK+ applications
Description :
webp-pixbuf-loader contains a plugin to load WebP images in GTK+ applications
```
![Screenshot at 2020-09-20 12-22-05](https://user-images.githubusercontent.com/10171411/93709192-85d28f80-fb3c-11ea-8a1e-9849579a2351.png)

**Comment by baryluk** [comment]
That is great. Thanks. 

Unfortunately webp-pixbuf-loader is not in Debian, Ubuntu. Yet. One step at a time :) PS. It is being requested: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951113 and https://salsa.debian.org/okias-guest/webp-pixbuf-loader looks to be updated few hours ago with some new stuff, so it is comming.


eog people also appears to be working on the support in their code, and made it to work with the same loader.

**Comment by lukefromdc** [comment]
Confirm we don't have it here in Debian Unstable yet

**Comment by silpol** [comment]
Current debian packaging can be found [here](https://salsa.debian.org/okias-guest/webp-pixbuf-loader)
via 
Debian Bug report logs - [#951113](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951113#10)
ITP: webp-pixbuf-loader -- WebP Image format GdkPixbuf loader.

**Comment by lukefromdc** [comment]
Just built the upstream package from source and it works: EOM can display WebP files with this installed
