### ISSUE TITLE
Blocker Crash at startup

### ISSUE THREAD

**Issue by Zaffy** [mate-desktop/eom#106]
Hey guys!

I'm running 64bit archlinux and I'm constantly getting this crash at startup.

```
Reading symbols from ./src/eom...done.
(gdb) run
Starting program: /home/mate/eom/src/eom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2f3babc in g_option_context_add_group () from /usr/lib/libglib-2.0.so.0
(gdb) bt full
#0  0x00007ffff2f3babc in g_option_context_add_group () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#1  0x0000000000420e13 in main (argc=1, argv=0x7fffffffe198) at main.c:212
        error = 0x0
        ctx = 0x7fffea84b260
(gdb) # g_irepository_get_option_group() does not return NULL...```
(gdb) print (void*) g_irepository_get_option_group()
$1 = (void *) 0xffffffffea8a0900
```

Revision is the latest:

```
commit e9d2568e62b0a46c5dd4a80eb3bc94383ebf290e
Author: raveit65 <chat-to-me@raveit.de>
Date:   Thu Oct 15 13:02:38 2015 +0200

    release 1.11.0
```

I tried to fix the crash myself but the only working solution was to remove that part from main.c completely.

**Comment by raveit65** [comment]
gir support is broken, compile it without it, see http://pkgs.fedoraproject.org/cgit/eom.git/tree/eom.spec#n93
Than everthing works.

**Comment by Zaffy** [comment]
Sure. As I mentioned I compiled without it and everything was working.
But if the support is broken shouldn't it be dropped off the code? Or at least be disabled by default?

**Comment by monsta** [comment]
I have introspection enabled and I've never seen such a crash in Debian/Ubuntu/Mint.

**Comment by monsta** [comment]
@Zaffy: please install debug package for glib and post the backtrace again (it should indicate the exact line inside ```g_option_context_add_group``` this time).

**Comment by Zaffy** [comment]
@monsta Hey, here's the log:

```
#0  g_option_context_add_group (context=0x7fffea84b260, 
    group=0xffffffffea8a0890) at goption.c:570
        _g_boolean_var_ = <optimized out>
        list = <optimized out>
        __func__ = "g_option_context_add_group"
#1  0x0000000000420e13 in main (argc=1, argv=0x7fffffffe248) at main.c:212
        error = 0x0
        ctx = 0x7fffea84b260
```
And here's a snipper for that line:

```
565	{
566	  GList *list;
567	
568	  g_return_if_fail (context != NULL);
569	  g_return_if_fail (group != NULL);
570	  g_return_if_fail (group->name != NULL);
571	  g_return_if_fail (group->description != NULL);
572	  g_return_if_fail (group->help_description != NULL);
573	
574	  for (list = context->groups; list; list = list->next)
```
Actually, I tried to dump the *group in gdb but it looks like it points to invalid memory, so first dereferencing makes it crash.

**Comment by monsta** [comment]
Looks weird... which glib version do you have?

**Comment by Zaffy** [comment]
2.46.1

**Comment by monsta** [comment]
Do you have any plugins (bundled or third-party) enabled?

**Comment by Zaffy** [comment]
What do you mean exactly?

**Comment by Zaffy** [comment]
This was my mistake, sorry. The problem was system-wide jemalloc. Thanks for quick support anyway.

**Comment by monsta** [comment]
Ok no problem :smile:
