### ISSUE TITLE
linking error due to undefined reference to symbol 'XGetScreenSaver'

### ISSUE THREAD

**Issue by oleid** [mate-desktop/eom#111]
Hey,

I experience a linking error on gentoo/arm:

    libtool: link: ( cd ".libs" && rm -f "libeom.la" && ln -s "../libeom.la" "libeom.la" )
    /bin/sh ../libtool  --tag=CC   --mode=link armv7a-hardfloat-linux-gnueabi-gcc -I../cut-n-paste/toolbar-editor -I../cut-n-paste/totem-screensaver -pthread -I/usr/include/mate-desktop-2.0 -I/usr/include/dconf -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/libexif -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16  -DEOM_DATA_DIR=\""/usr/share/eom"\" -DEOM_LOCALE_DIR=\""/usr/share/locale"\" -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/lib/libffi-3.0.13/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -O2 -pipe -march=native -mfpu=neon-vfpv4 -mfloat-abi=hard  -Wl,-O1 -Wl,--as-needed -o eom eom-main.o libeom.la -ljpeg ../cut-n-paste/toolbar-editor/libtoolbareditor.la ../cut-n-paste/totem-screensaver/libtotemscrsaver.la ../jpegutils/libeom-jpegutils.la -lgirepository-1.0 -lgobject-2.0 -lglib-2.0  -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgthread-2.0 -pthread -lmate-desktop-2 -lstartup-notification-1 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lexif -ldbus-glib-1 -ldbus-1 -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo  -lm -lz
    libtool: link: armv7a-hardfloat-linux-gnueabi-gcc -I../cut-n-paste/toolbar-editor -I../cut-n-paste/totem-screensaver -pthread -I/usr/include/mate-desktop-2.0 -I/usr/include/dconf -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/libexif -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -DEOM_DATA_DIR=\"/usr/share/eom\" -DEOM_LOCALE_DIR=\"/usr/share/locale\" -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/lib/libffi-3.0.13/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -O2 -pipe -march=native -mfpu=neon-vfpv4 -mfloat-abi=hard -Wl,-O1 -o eom eom-main.o -Wl,--export-dynamic -pthread -pthread  -Wl,--as-needed ./.libs/libeom.a -ljpeg ../cut-n-paste/toolbar-editor/.libs/libtoolbareditor.a -lxml2 ../cut-n-paste/totem-screensaver/.libs/libtotemscrsaver.a ../jpegutils/.libs/libeom-jpegutils.a -lgirepository-1.0 -lgmodule-2.0 -lgthread-2.0 -lmate-desktop-2 -lstartup-notification-1 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lexif -ldbus-glib-1 -ldbus-1 -lrsvg-2 -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo -lm -lz -pthread
    /usr/lib/gcc/armv7a-hardfloat-linux-gnueabi/4.9.3/../../../../armv7a-hardfloat-linux-gnueabi/bin/ld: ../cut-n-paste/totem-screensaver/.libs/libtotemscrsaver.a(libtotemscrsaver_la-totem-scrsaver.o): undefined reference to symbol 'XGetScreenSaver'
    /usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    Makefile:751: recipe for target 'eom' failed

If I add `-lX11` at the very and of the linking command line, everything links fine. Indeed, a `-lX11` is missing in `libtotemscrsaver.la`. This is the case due to `X11_LIBS` being unset in the Makefile.

The variable is usually set in the configure script:

    [...]
    # Check GDK rendering target
    gdk_target=`$PKG_CONFIG --variable=target gdk-${GTK_API_VERSION}`
    
    if test "x$have_lcms" = "xyes" || test "$gdk_target" = "x11"; then
    [...]

Since I don't use lcms, the check `"$gdk_target " = "x11"` needs to be `true`. It seems as if the pkgbuild variable got renamed for GTK+3.0 from `target` to `targets`. This is my pkg-config file on the arm machine:

```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include
targets=x11

Name: GDK
Description: GTK+ Drawing Kit
Version: 3.16.6
Requires: pango pangocairo gdk-pixbuf-2.0 >= 2.30.0 cairo >= 1.14.0 cairo-gobject >= 1.14.0
Requires.private: gio-unix-2.0 >= 2.43.4 fontconfig x11 xext xi xrandr xcursor xfixes xcomposite xdamage    cairo-xlib epoxy >= 1.0 pangoft2
Libs: -L${libdir} -lgdk-3 
Cflags: -I${includedir}/gtk-3.0
```

And for reference, this is the corresponding gdk-3.0.pc on ArchLinux/amd64:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
targets=x11 broadway wayland

Name: GDK
Description: GTK+ Drawing Kit
Version: 3.18.4
Requires: pango pangocairo gdk-pixbuf-2.0 >= 2.30.0 cairo >= 1.14.0 cairo-gobject >= 1.14.0
Requires.private: gio-unix-2.0 >= 2.45.8 fontconfig x11 xext xinerama xi xrandr xcursor xfixes xcomposite xdamage wayland-client >= 1.5.91 xkbcommon >= 0.2.0 wayland-cursor >= 1.5.91 wayland-egl   cairo-xlib cairo cairo epoxy >= 1.0
Libs: -L${libdir} -lgdk-3 
Cflags: -I${includedir}/gtk-3.0
```

The following patch works for me:
```
diff -Nur eom-1.12.0.orig/configure.ac eom-1.12.0/configure.ac
--- eom-1.12.0.orig/configure.ac        2015-11-02 21:59:58.000000000 +0100
+++ eom-1.12.0/configure.ac     2015-11-13 19:25:50.249996358 +0100
@@ -343,9 +343,13 @@
 # *******************************************************
 
 # Check GDK rendering target
-gdk_target=`$PKG_CONFIG --variable=target gdk-${GTK_API_VERSION}`
+if test "${GTK_API_VERSION}" = "2.0" ; then
+       gdk_target_has_x11=`$PKG_CONFIG --variable=target gdk-${GTK_API_VERSION} | grep x11`
+else
+       gdk_target_has_x11=`$PKG_CONFIG --variable=targets gdk-${GTK_API_VERSION} | grep x11`
+fi
 
-if test "x$have_lcms" = "xyes" || test "$gdk_target" = "x11"; then
+if test "x$have_lcms" = "xyes" || test "$gdk_target_has_x11" != ""; then
        PKG_CHECK_MODULES(X11, [x11], have_x11=yes, have_x11=no)
 
        if test "x$have_x11" != "xyes"; then
```

**Comment by monsta** [comment]
Thanks, merged in https://github.com/mate-desktop/eom/commit/f8426fec9de47f2fdcc73f8ead03f282955d7982.
