### ISSUE TITLE
EOM does not have a keyboard shortcut to open the "Help" menu

### ISSUE THREAD

**Issue by physicsshark** [mate-desktop/eom#112]
![screenshot73](https://cloud.githubusercontent.com/assets/9755486/11461648/83979f38-96d5-11e5-967a-c145668ea12b.png)
With EOM 1.12.0, I noticed there is no keyboard shortcut (or the associated mnemonic) for the "Help" menu.  This is inconsistent with the other MATE applications and a little bit annoying.

**Comment by monsta** [comment]
Works for me...

**Comment by physicsshark** [comment]
We're talking about the Alt +h shortcut right?  That's the one that's not
working for me.

**Comment by monsta** [comment]
Yes, Alt-H is working here, and the H letter in Help is underlined...

**Comment by raveit65** [comment]
The sequence pressing alt+h  and than n
opens here in fedora the help page.

**Comment by monsta** [comment]
Nevermind, I found out what happens. My locale is Russian, so when I've tried to reproduce the issue, I've used ```LC_ALL=C eom``` to make UI appear in English. But the issue actually was in en_US locale... running ```LC_ALL=en_US.UTF-8 eom``` helped to reproduce it.

Indeed, Help and Tools (the latter can be toggled by enabling "Reload image" plugin) have this issue.

**Comment by raveit65** [comment]
and same boring question....which distro?

**Comment by monsta** [comment]
There are a few more menu items w/o shortcuts in en_US locale... and strings on Transifex seem to be alright. Guess I'll push a quick fix for now.

**Comment by monsta** [comment]
There, https://github.com/mate-desktop/eom/commit/a4d162e07198350693d651a868dbf6981eb00295 should fix it.
