### ISSUE TITLE
GTK+3: SVG images render far above intended position

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/eom#117]
At least in GTK 3, rendering of .svg images is well above their intended position with an empty alpha image area shown where the image should be. Zooming in will show the bottom portion of the image in the top part of the view.  I was able to fix this by reverting one commit from the 1.10.3 days, yielding this PR:

https://github.com/mate-desktop/eom/pull/116

**Comment by monsta** [comment]
Can you attach a sample image so that I could try it in GTK+2 build?

**Comment by lukefromdc** [comment]
Here are two SVG icons, shown on the left with current git master and
on the right with my fix. Does anyone know a better way to do this, given
a complaint about double buffering being needed for very large images?

Perhaps a runtime switch to turn it off if a .svg image is loaded?

**Comment by lukefromdc** [comment]
Here is the image of what double-buffering does to SVG rendering without some other change to either move them back or turn it off for SVG images only:

![svg_image_bug](https://cloud.githubusercontent.com/assets/14036792/12345283/ae790a26-bb14-11e5-878e-bc68e0cdfeae.png)

**Comment by monsta** [comment]
Well I've tried a few 16x16 svg icons from Mint-X icon theme... they're still centered when zoomed. That's in GTK+2 build though.

![eom-1](https://cloud.githubusercontent.com/assets/5138986/13285423/90756bac-db0b-11e5-9211-099575a93697.png)
![eom-2](https://cloud.githubusercontent.com/assets/5138986/13285425/93def36c-db0b-11e5-894d-eb89c743ddaf.png)

**Comment by monsta** [comment]
Ok, I confirm GTK+3 build (with 3.18.7) is affected by this bug:

![eom-3](https://cloud.githubusercontent.com/assets/5138986/13285817/ff07f600-db0d-11e5-8e3d-51fb6c69c88b.png)
![eom-4](https://cloud.githubusercontent.com/assets/5138986/13285819/01c7c00a-db0e-11e5-99de-d1cf68f14b19.png)

**Comment by monsta** [comment]
I've tested eog 3.18.2 in the same VM - it shows these icons correctly, and they didn't revert the double buffer commit... :confused:

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/eom/pull/118 works fine on my system with gtk3.19.9, fixes the SVG rendering issue and I didn't notice any new problems in a quick test
