### ISSUE TITLE
"image-collection-position" broken

### ISSUE THREAD

**Issue by styxxx** [mate-desktop/eom#123]
Hello,

I already filed a bug via the debian bug tracking system a while ago (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818455#) but it's not a Debian issue and I'm not sure if anyone notices the reports there. Since you asked on the github page to file reports here I'm posting it here again ;)

The position of the image collection can't be set anymore. In the past you
could set an integer value with dconf:
http://git.mate-desktop.org/eom/tree/data/org.mate.eom.gschema.xml.in.in?h=1.6&id=c38cb72f0b012c83032b54ad2062ea6893e0a554
With 0 (default) for bottom, 1 for left, ...

```
    <key name="image-collection-position" type="i">
      <default>0</default>
      <_summary>Image collection pane position. Set to 0 for bottom;  1 for left; 2 for top; 3 for right.</_summary>
    </key>
```

This seems to have been changed to an "enum" value:
https://github.com/mate-desktop/eom/blob/master/data/org.mate.eom.gschema.xml.in#L7

```
  <key name="image-collection-position" enum="org.mate.eom.EomWindowCollectionPos">
      <default>'bottom'</default>
      <summary>Image collection pane position.</summary>
   </key>
```

Unfortunately dconf still only accepts numeric values. Even the standard value
"bottom" is not accepted. Also I think a descripton or at least hint in the
summary about the accepted values should be added. A previously set numeric
value is kept and not converted (but not working anymore of course).

I couldn't find a definition of "_org.mate.eom.EomWindowCollectionPos_". Maybe
it's missing?

Thanks :)

**Comment by raveit65** [comment]
Hmm,
[rave@mother ~]$ gsettings get org.mate.eom.ui image-collection-position
'bottom'
this works here with eom-1.14.0 in fedora 24.
Same with eom-1.12.2 in fedora-23

**Comment by raveit65** [comment]
@sunweaver 
Can you you reproduce the issue?

**Comment by monsta** [comment]
Just tested it, works perfectly for all four position values here (eom 1.14.2 in Mint 18).
