### ISSUE TITLE
A large 102 MB jpg file causes EOM to crash.

### ISSUE THREAD

**Issue by aakashysharma** [mate-desktop/eom#127]
EOM Version 1.12.2

When I tried opening downloaded copy (full-size) of this image [https://www.flickr.com/photos/joxeankoret/27365679222/in/album-72157666630736933/](https://www.flickr.com/photos/joxeankoret/27365679222/in/album-72157666630736933/) , EOM crashes abruptly.

It tries to open, I could see progress bar moving but near the end, it just crashes and closes itself without displaying any error.

**Comment by aakashysharma** [comment]
Maybe similar to #105

**Comment by flexiondotorg** [comment]
In fact a duplicate of #105 :-)
