### ISSUE TITLE
Load TGA images

### ISSUE THREAD

**Issue by jEsuSdA** [mate-desktop/eom#129]
EOM has no TGA images support, but EOG has.
So, I don't know if this is a bug or is a feature request. ;)

So, please, if you can, add or activate TGA support, please.

Thanks for your work! ;)
##

**Comment by monsta** [comment]
Did you try them both on the same system? Because I suspect that support for it is actually in gdk-pixbuf library...

**Comment by flexiondotorg** [comment]
No feedback.
