### ISSUE TITLE
Light problem in .svg picture

### ISSUE THREAD

**Issue by tele1** [mate-desktop/eom#135]
I see problem with this icon , uplos.svg
http://s000.tinyupload.com/index.php?file_id=77452206423555214363

If you can download for check

In firefox exist light, with oem  not
or I see when I Zoom in,  Zoom out image.

Mate 1.16.1  gtk3 , Manjaro 64bit

Can you check this icon ?
Thanks.

Edited.

__________________________________________________________
Bounty spam ...
https://www.bountysource.com/issues/39803581-light-problem-in-svg-picture?utm_campaign=plugin&utm_content=tracker%2F1187514&utm_medium=issues&utm_source=github

_What is a bounty?
A bounty is a cash reward offered for development. In the case of Bountysource, this ties directly to an open issue in the system.
Who can post a bounty?_

_Anybody with PayPal, Bitcoin, or funds in their Bountysource account (such as earning money from a previous bounty). Note: Google has discontinued Google Wallet for Digital Goods, so we are no longer able to offer that as a payment option._
______________________________________________________________

**Comment by MatheusGASource** [comment]
Also I use manjaro x64 and eom 1.16.0, when I open image in svg it gets very slow to the point of being unusable.

**Comment by sbalneav** [comment]
Just checked, the problem also exists in eog.  I suspect the problem isn't in either eom, or eog, but rather in librsvg itself.

**Comment by tele1** [comment]
Maybe its true with  librsvg.
Because firefox don't use  librsvg,   eog use.
I will try write to  librsvg bugzilla  , but don't know when. 
Before write I need also test newer  librsvg.

However , 
- this bug exist also on Debian 8.8  ( librsvg2-2    2.40.5-1 + deb8u2 )
- thanks for help :-)

**Comment by raveit65** [comment]
Does the issue still exists with latest eom-1.20.x ?
Btw. the svg-image link doesn't exists any more.

**Comment by tele1** [comment]
I will check in free time.
For now you can check alone,
 search icon .svg inside ./usr/share/icons/uplos/scalable/places/
https://ftp.nluug.nl/os/Linux/distr/uplos/32bit/RPMS.updates/uplos-icon-theme-2-2uplos.noarch.rpm

Enlarge and shrink the icon,
 you will see: 
- light is round like in https://www.youtube.com/watch?v=rNvDgDeV53c
and with shrinks and expands you can resize picture and  light like via telescope

Of course, in this picture, the light is not evenly bright,
because it should not,
 but you will see as if an additional filter was placed.
Telescope filter, and with resize picture you can resize this filter,
but this is not Gimp :smile: 

Once I wanted to report a bug with librsvg on Debian, but I had few problems,
- mailing list show real email for spamers
- forum dynamic IP blocks
- I also had a problem with reporting an error from app.
I did not have time for configure VPN or create new email for spam.

**Comment by raveit65** [comment]
![uplos-logo-eom-firefox](https://user-images.githubusercontent.com/961604/42533806-2d3d58fc-848b-11e8-9219-96a31fd70c35.png)
With current eom from master and firefox-61.0-4.fc28.x86_64
Should is see a different of more light?
[rave@mother ~]$ rpm -qa librsvg2
librsvg2-2.42.3-1.fc28.x86_64

**Comment by tele1** [comment]
They look identical with light.
That's good :smiley: 

My ( with old mate, have light  truncated.
http://oi64.tinypic.com/bj8z9t.jpg
if I will give a full screen, light disappears.

If you resize picture and light is the same, this working now.

**Comment by raveit65** [comment]
I rechecked it again with latest stable released eom-1.20.1 and the light is fine.
