### ISSUE TITLE
eom auto reload file is broken

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/eom#137]
Forwarding https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816914 ...

Package: eom
Version: 1.12.2-1

1) Open some jpg file in Eye of MATE.
2) Don't close Eom window. Open same file in Gimp.
3) Change file in Gimp and save it. Of course, via file->overwrite
test.jpg, not via ctrl+s.

What I'm expected: Eom at least ask "File changed. do you want reload
it?" (it's work in Jessie).
What I'm got: in one file Eom window turn black. In other file - Eom
simply ignore file changing.

**Comment by monsta** [comment]
Weird... I'm pretty sure it worked in some recent versions, but now I tried again, and it doesn't work in 1.16 or 1.17.

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/eom/commit/25f76643b789f466694177e79cf1bc36edf508de fixes it, thanks to upstream. I will backport it to 1.16 branch as well.
