### ISSUE TITLE
EOM crashes on large jpeg

### ISSUE THREAD

**Issue by rolandm1234** [mate-desktop/eom#138]
trying to open 60 MByte picture of Rom https://upload.wikimedia.org/wikipedia/commons/5/5e/View_from_Stpeters_bottomcropped.jpg EOM crashes:
The program 'eom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 60301 error_code 11 request_code 130 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(Shotwell opens picture without problems)
OS: Ubuntu 16.04, Mate 1.12.1, Intel Skylake graphics

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/eom/commit/ad32b4d69a5a56d416502fb2e3bb5f2c1e6a605c. Please file a bug report on Launchpad and then @flexiondotorg might be able to submit the patch to Ubuntu.
