### ISSUE TITLE
Feature request: double click image to make it full screen

### ISSUE THREAD

**Issue by MarioMey** [mate-desktop/eom#147]
As I'm (we're) used to, when I play a video, double click the video/windows to make it full screen.

I found me, several times, double-clicking the EOM windows and expecting full screen :P.

Can it be a feature?

My system: Ubuntu-Mate 16.04 64x.

**Comment by raveit65** [comment]
Hmm, why not using F11 key for toggling fullscreen, which is much faster than using a mouse?

**Comment by MarioMey** [comment]
Yes, I know that F11 is the full-screen-key... but it is far away from left hand (that it is always in the keyboard). I mean, I have to see the keyboard before pressing that key.

I use EOM from Caja. If press Enter in the file, my hand is near F11... but my fingers has to "explore" F9, F10, F11, F12, the space between F12-PrintScreen and PrintScreen key... to find F11. It takes a little while. If I double click in the file (most of times), the best way to set it full screen, IMHO, is by double clicking the image.

F11 does not go to full-screen the video in VLC. It turns the window full-screen (menu and controls visible). Also, ESC key does not go back to window... F11 again does it.

**Comment by monsta** [comment]
Isn't the bundled fullscreen plugin enough for the task? :confused:

**Comment by MarioMey** [comment]
Yes, man. I didn't know about that. Sorry, close this ticket.
