### ISSUE TITLE
Delete image on a file system with no trash

### ISSUE THREAD

**Issue by UnoSD** [mate-desktop/eom#150]
#### Expected behaviour
Hitting delete on an image should bring up the dialog (warning it is going to be permanent) and delete the image on confirmation

#### Actual behaviour
Error on deleting image
Couldn't access trash.

#### Steps to reproduce the behaviour
Open an image on ~NTFS or~ any trash-less file system (including network FS)

#### MATE general version
Eye of MATE 1.12.2

#### Package version
1.12.2-r3

#### Linux Distribution
Gentoo

**Comment by raveit65** [comment]
Hmm, i don't see an option in eom menu to delete a file.
We have only save/save as.
Please explain exactly what you mean.

**Comment by UnoSD** [comment]
If you hit the delete key while viewing an image, it moves it to the trash (where the fs supports it).

**Comment by raveit65** [comment]
Hmm, it works here with a ntfs filesystem.
![eom-delete-file](https://user-images.githubusercontent.com/961604/42678330-db621a36-867e-11e8-85d6-5efe9cb360bd.jpg)

**Comment by UnoSD** [comment]
Yeah, when I added the support for trash to my NTFS, it worked, too. If I remove it I get the error back. The issue is still valid when trash is not available. I'll update it.

**Comment by raveit65** [comment]
Yes i mounted the ntfs partition via /etc/fstab
```
# /dev/nvme0n1p4
UUID=xxxxxxxxxxxxxxx /media/Win10 ntfs defaults,noauto 0 0
```
You mean with smb share?
I think we have already an open report for samba shares.

**Comment by raveit65** [comment]
Btw. Does Eye of gnome have the same behaviour?

**Comment by UnoSD** [comment]
Yes, now I have this problem with samba shares (but I used to have it also for NTFS when I didn't have the trash available so it's not samba specific). Not sure about EOG as I haven't used it in a while.

**Comment by raveit65** [comment]
Well, i don't have a file system without trash for testing.
And the warning that i get is for the trash, so isn't it logic to see no warning without using a trash?
Sounds for me more like a new feature which isn't implemented.
Would be interessting to know if it works with eog for you?

**Comment by UnoSD** [comment]
I can use my old laptop with Gnome and give it a try.

> In Caja I get dialogs on some filesystems about a file that can't be moved to trash and offering the option to delete it right away.

I think ideally it should be the same from the app.

**Comment by raveit65** [comment]
> I can use my old laptop with Gnome and give it a try.

Eog should be able to install on every gentoo box, or not?

**Comment by UnoSD** [comment]
@raveit65 It says: "A trash fox the image could not be found, do you want to delete the image permanently?"

**Comment by UnoSD** [comment]
it actually worked on EOM as well, the only issue seemed to be on NTFS when it did not have permissions, I'll close the issue, that sounds too much of an edge case to keep it open.
