### ISSUE TITLE
crash with wide image

### ISSUE THREAD

**Issue by splace** [mate-desktop/eom#153]
#### Expected behaviour
display it, like firefox, chrome and shotwell do.

#### MATE general version
Eye of MATE 1.12.2

#### Linux Distribution
Ubuntu mate 16.04 

#### Command line message 
The program 'eom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 507 error_code 11 request_code 130 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

#### Example file, one that isn't being displayed
![oscillator](https://user-images.githubusercontent.com/1234848/32139722-db364ce4-bc49-11e7-8d70-82d63f502dc8.png)

**Comment by raveit65** [comment]
The image opens fine here with eom-1.19.1-1.fc26.x86_64 on fedora 26
Btw. i am in doubt that Ubuntu 16.04 will ever get updates, I suggest to switch to a Ubuntu-MATE release with actual MATE packages. 
@flexiondotorg 
reproducible?

**Comment by monsta** [comment]
This is tricky... I get latest eom crashing in a Debian Testing VM with 3 Gb RAM. It doesn't happen on baremetal with 8 Gb. That said, system monitor shows eom using only about 120 Mb after that image is loaded. I have no idea why it tries to allocate a lot more than that (BadAlloc most probably means "not enough memory").

**Comment by alexarnaud** [comment]
I can reproduce the exact same issue on Debian Sid with eom 1.20 with this svg image : https://github.com/FabioLolix/LinuxTimeline/releases/download/v16.12/gldt_v16.12.svg

See this downstream report : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893764

I suspect a memory leak, on Mate 1.8 with the same image, eom takes 150M of RAM and with eom 1.20 it takes 400M. In Mate 1.8 the opening of the image is very fast (2s) and with 1.20 it takes 20s.

Best regards,
Alex.

**Comment by monsta** [comment]
Debian Stretch, eom built from git master, image loaded successfully. I confirm very slow loading and 400 Mb of RAM. No crashes though. This system has 6 Gb RAM, this was probably enough to not crash with BadAlloc.
