### ISSUE TITLE
Please update appstream metadata file: eom.appdata.xml for 1.20

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/eom#154]
W: eom-common: appstream-metadata-in-legacy-location usr/share/appdata/eom.appdata.xml
N: 
N:    AppStream metadata file was found in /usr/share/appdata/. The AppStream
N:    XML files should be placed in /usr/share/metainfo/.
N:    
N:    Refer to https://wiki.debian.org/AppStream/Guidelines for details.
N:    
N:    Severity: minor, Certainty: certain
N:    
N:    Check: appstream-metadata, Type: binary
N: 
E: eom-common: appstream-metadata-legacy-format usr/share/appdata/eom.appdata.xml
N: 
N:    AppStream metadata with obsolete <application> root node found. This
N:    indicate a legacy format. The metadata should follow the format the new
N:    outlined on the freedesktop.org homepage.
N:    
N:    It is possible to validate the format using 'appstreamcli validate'.
N:    
N:    Refer to https://wiki.debian.org/AppStream/Guidelines and
N:    https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
N:    for details.
N:    
N:    Severity: important, Certainty: certain
N:    
N:    Check: appstream-metadata, Type: binary
N:

**Comment by raveit65** [comment]
@sunweaver 
PR please.
I have no idea to update that but i can merge a PR.

**Comment by sunweaver** [comment]
Hi,

On Sunday, July 8, 2018, raveit65 wrote:
> @sunweaver 
> PR please.
> I have no idea to update that but i can merge a PR.
 
I have no clue either, how to fix that, but I can put it on my list.

Mike

-- 
Sent from my Fairphone (powered by SailfishOS)

**Comment by monsta** [comment]
This should be fixed with https://github.com/mate-desktop/eom/commit/e3a9345070fb3aff34ca9364c6eb732bd769864e - should we close this?

@sunweaver: I saw there are Debian patches for the same issue in other packages - but not in eom. Was there some reason for it? Just curious as I'm updating [debian-packages](https://github.com/mate-desktop/debian-packages) repo.

**Comment by sunweaver** [comment]
Hi,

On  Di 18 Dez 2018 14:35:09 CET, monsta wrote:

> This should be fixed with  
> https://github.com/mate-desktop/eom/commit/e3a9345070fb3aff34ca9364c6eb732bd769864e - should we close  
> this?
>
> @sunweaver: I saw there are Debian patches for the same issue in  
> other packages - but not in eom. Was there some reason for it? Just  
> curious as I'm updating  
> [debian-packages](https://github.com/mate-desktop/debian-packages)  
> repo.

AFAIR, I did not patch any file content. I simply moved files from  
their "old" location to their "new" canonical location.

All file movals take place in debian/rules. Can't remember for what  
components I had to do that... Mostly the applications (pluma,  
engrampa, caja, etc.).

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by monsta** [comment]
Right... it's in the rules file, I should've been more clear. So, in eom's rules file it's not done.

**Comment by sunweaver** [comment]
Hi,

On Tuesday, 18 December 2018, monsta wrote:
> Right... it's in the rules file, I should've been more clear. So, in eom's rules file it's not done.
> 

The appstream file format for eom was legacy format, so I did not bother moving it.

See:
https://lintian.debian.org/maintainer/debian-mate@lists.debian.org.html#eom

Cheers,
Mike 
-- 
Sent from my Jolla

**Comment by monsta** [comment]
Ah, I guess it's the root node name, as described in https://github.com/mate-desktop/eom/pull/197.

**Comment by sunweaver** [comment]
On  Mi 19 Dez 2018 12:00:43 CET, monsta wrote:

> Ah, I guess it's the root node name, as described in  
> https://github.com/mate-desktop/eom/pull/197.

Yep. Looks like it.

Can you pull-over those changes to the upcoming 1.20 minor release of  
thos components (in case you haven't done so).

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by monsta** [comment]
Sure, cherry-picked in https://github.com/mate-desktop/eom/commit/540e33ffe06e7608ea539e7db79170d6cc8cb041.
