### ISSUE TITLE
“Set as Desktop Background” seems inefficient or incomplete

### ISSUE THREAD

**Issue by ghost** [mate-desktop/eom#161]
#### Expected behaviour

Setting a picture as desktop background, on whatever desktop environment or window manager. While it seems to work fine on Mate, Gnome, etc., it simply doesn’t work on AwesomeWM, Fluxbox, PekWM, JWM, WindowMaker etc.

It should do the same as the command line “fbsetbg -f picture.jpg” would do.

Perhaps this function only affects that OpenDesktop-xml-registry-thing used from Mate, Gnome and etc (i forgot the name used for that). The idea would be if this could also run “fbsetbg -f”

Another idea would be if we could have scripts available from the menu, just like what we have available from Caja (normally i apply desktop backgrounds from there, a script that runs “fbsetbg -f” from a selected picture file)

#### Actual behaviour

Nothing happens on AwesomeWM, Fluxbox, PekWM, JWM, WindowMaker etc.

#### Steps to reproduce the behaviour

choose a picture, and from the menu select “Image/Set as Desktop Background”

#### MATE general version

where do i find it? i don’t have Mate installed (i’m mostly using AwesomeWM instead), only EOM, Caja, Engrampa, Pluma, Mate-Terminal, etc.

#### Package version

1.18.2-1 (Ubuntu, perhaps Debian as well)

#### GNU/Linux Distribution

Ubuntu

#### Link to downstream report of your Distribution

where from can i find that?

**Comment by raveit65** [comment]
Closing as ghost is a non existing user.
