### ISSUE TITLE
EoM not reading embeded color profiles.

### ISSUE THREAD

**Issue by dgsan** [mate-desktop/eom#170]
#### Expected behaviour
Opening an image with a color profile uses the color profile (Adobe RGB, etc.).

#### Actual behaviour

Adobe RBG jpegs look flat, it seems to be reading them as sRGB.

#### Steps to reproduce the behaviour
Open a RAW in Darktable.

Adjust (make sure it has some warm tones in part). Export it once with sRGB, export it once with Adobe RGB.

Open each with EoM, compare to the image you see in Darktable.

#### MATE general version
1.20.0

#### Package version
1.20.0-2ubuntu1

#### Linux Distribution
Ubuntu MATE 18.04

**Comment by raveit65** [comment]
Example file please?

**Comment by rcaridade145** [comment]
@raveit65 @dgsan Eye of gnome seems to use this reasoning also https://bugzilla.gnome.org/show_bug.cgi?id=554498

**Comment by raveit65** [comment]
Without an example file i can't try to back port a possible fix.

**Comment by mareg** [comment]
Here's an example - GIMP in the back, EOM at the Front:
![GIMP vs EOM - colour rendering comparison](https://pub.megaloman.org/colour/gimp-vs-eom.png)
Source image: https://www.dropbox.com/s/juea9tbgz9wohz9/PrinterEvaluationImage_V002_ProPhoto.tif?dl=0 (42.2 MB)

**Comment by mareg** [comment]
Is it because [LCMS is disabled by default](https://github.com/mate-desktop/eom/blob/master/configure.ac#L162)? Maybe it should be enabled by default?

**Comment by mareg** [comment]
Tried to build `eom` with LCMS enabled, got the following error:
```
configure: error: Package requirements (gtk+-3.0 >= 3.22.0              glib-2.0 >= 2.50.0              gmodule-2.0              gio-2.0 >= 2.50.0              gio-unix-2.0 >= 2.50.0              gthread-2.0 >= 2.50.0              mate-desktop-2.0 >= 1.17.0              gdk-pixbuf-2.0 >= 2.30.0              gio-2.0 >= 2.50.0              gtk+-unix-print-3.0 >= 3.22.0              shared-mime-info >= 0.20              libpeas-1.0 >= 1.8.0              libpeas-gtk-1.0 >= 1.8.0 lcms2 librsvg-2.0 >= 2.36.2) were not met:

Package 'gtk+-3.0', required by 'virtual:world', not found
Package 'mate-desktop-2.0', required by 'virtual:world', not found
Package 'gtk+-unix-print-3.0', required by 'virtual:world', not found
Package 'libpeas-1.0', required by 'virtual:world', not found
Package 'libpeas-gtk-1.0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables EOM_CFLAGS
and EOM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
I don't seem to have `mate-desktop` version `2.0` available? :thinking:

**Comment by vkareh** [comment]
@mareg - lcms is enabled by default, it only gets disabled if you don't have the lcms2 library.

**Comment by mareg** [comment]
@vkareh any tips how to build it from the source code? I have both lcms2 and lcms2-devel installed, yet build fails for me.
```
$ rpm -qa | grep lcms2
lcms2-2.9-5.fc30.x86_64
lcms2-devel-2.9-5.fc30.x86_64
```

**Comment by mareg** [comment]
Ok, managed to compile, still does not seem to respect monitor profile.

See example: gimp on the left, eom on the right:
![screenshot22](https://user-images.githubusercontent.com/533217/61485560-5acd3880-a999-11e9-81ed-565055a1eab5.png)

**Comment by mareg** [comment]
Just to confirm, eom built from the source (with fixed from PR #234) now reads embedded colour profiles correctly:
![screenshot23](https://user-images.githubusercontent.com/533217/61485783-f363b880-a999-11e9-81e1-899dc8f05cd6.png)
But it doesn't apply monitor profile, so colours in EOM appear slightly oversaturated (on my monitor) - the wider gamut monitor, the more visible difference to user will be in saturation.

**Comment by raveit65** [comment]
@mareg 
Here is a ready built rpm for fedora 30
https://koji.fedoraproject.org/koji/taskinfo?taskID=36337902

**Comment by mareg** [comment]
> @mareg
> Here is a ready built rpm for fedora 30
> https://koji.fedoraproject.org/koji/taskinfo?taskID=36337902

Thanks @raveit65 embedded profile is read and applied correctly, but monitor's profile is not used - so same effect as in https://github.com/mate-desktop/eom/issues/170#issuecomment-512951677
