### ISSUE TITLE
Details list view in Image Properties does not resize

### ISSUE THREAD

**Issue by mvglasow** [mate-desktop/eom#214]
#### Expected behaviour

Tabs in Image Properties dialog fills the entire window; both tab its content resizes with the window. List view in Details tab fills the entire tab.

#### Actual behaviour

Works for width but height of tabs seems fixed. Details list view occupies less than half the available height, allowing for only four lines of content (despite there being much more content). Also, the vertical scroll bar does not seem to reflect the actual amount of content. See attached screenshot:

![screenshot](https://user-images.githubusercontent.com/2377496/53346690-ceea3f80-3917-11e9-95c2-041adca244c2.png)

#### Steps to reproduce the behaviour

1. Open an image with EXIF data in EOM.
2. Select **Image > Properties** from the menu.
3. Go to the Details tab.
4. Resize the window.
5. Scroll around in the list view

#### MATE general version

1.20.1

#### Package version

1.20.0-2ubuntu1

#### Linux Distribution

Ubuntu MATE 18.04

#### Link to downstream report of your Distribution

No downstream report (if you require one, let me know and I will open one).

**Comment by mixmastamyk** [comment]
Yeah this is bugging me too, doing a lot of photo work right now.  Have to use the clumsy gthumb to read exif data.

**Comment by raveit65** [comment]
Already fixed since a long time https://github.com/mate-desktop/eom/commit/cfc83b480d4a4577f8b6fcec818a4d63f6b2bb7e
You need to update to eom-1.22 .......

> #### Link to downstream report of your Distribution
> No downstream report (if you require one, let me know and I will open one).

...or asked ubuntu to update eom for your ubuntu release.
