### ISSUE TITLE
Clicking next/previous skips raw cr2 images

### ISSUE THREAD

**Issue by positroni** [mate-desktop/eom#218]
#### Expected behaviour
Clicking next or previous button in the UI should jump on all images type contained in a folder. Be them JPEG or raw

#### Actual behaviour
When pressing said buttons the program jumps to the next non-raw image

#### Steps to reproduce the behaviour
1 - Open a raw cr2 image in a folder with a mix of cr2 and JPEG images
2 - Click on the next or previous button
3- Notice that EoM skips cr2 images and show only JPEG

#### MATE general version
not-applicable

#### Package version
1.22.0

#### Linux Distribution
Archlinux

#### Link to downstream report of your Distribution
not applicable

**Comment by lukefromdc** [comment]
Do you have a test image (not too big MB wise) you can post? I do not have any cameras shooting to RAW and that might be true for other devs here too

**Comment by vkareh** [comment]
@lukefromdc - This website that has samples of RAW file formats for different cameras: https://raw.pixls.us (this is the website that the darktable team uses to test stuff)

There's a repository and you can type CR2 in the search box. In searching there, it turns out that this issue happens with several other types of formats too...

**Comment by vkareh** [comment]
A few notes:
* This issue happens with eog as well
* When eom is opened, it reads the list of files in the current directory and adds the supported ones to a list (using next/prev moves through that list)
* This function: [gdk_pixbuf_get_formats](https://github.com/mate-desktop/eom/blob/master/src/eom-image.c#L2193) returns the list of supported formats used to make this decision. The supported formats depend on which GdkPixbuf modules you have installed on your computer. Mine returns this list:
```
* png
* wmf
* ani
* bmp
* gif
* icns
* ico
* jpeg2000
* jpeg
* pnm
* qtif
* svg
* tga
* tiff
* xbm
* xpm
```
So I then installed `libopenraw-pixbuf-loader` (Fedora 29) and the list now shows this new entry (in addition to the old ones):
```
* Digital camera RAW
```
Now when doing Next to a RAW image, `eom` crashes with a Segfault. Not only that, if I open the RAW image directly with `eom`, it sometimes crashes, and sometimes shows the image in the wrong colors... _very_ strange. Exact same behavior with `eog`.

Anyway, I uninstalled the libopenraw-pixbuf-loader... :stuck_out_tongue:

**Comment by davidedelvento** [comment]
Is there any way to **NOT** include some of the (raw) extensions? In some (huge) directory the fact that EOM navigates everything makes it basically useless for me. It would have been much better if it used only the file types for which the OS has assigned EOM as default application.
