### ISSUE TITLE
Not asking if to delete images

### ISSUE THREAD

**Issue by es20490446e** [mate-desktop/eom#226]
Right now if while looking at an image you press "supr", you are asked if to delete the image.

I think it would be just more straightforward moving the image to the bin without further questions.

**Comment by vkareh** [comment]
This change would violate Human Interface Guidenline 3.4.6: [Confirmation Alerts](https://developer.gnome.org/hig-book/2.32/hig-book.html#alerts-confirmation)

**Comment by es20490446e** [comment]
It won't destroy their data, just move it to the bin. Actually the screen-shot on the guidelines shows a case were the data cannot be moved to the bin, just destroyed.

**Comment by es20490446e** [comment]
The current implementation of eom is a misunderstanding of the guidelines.

Nevertheless the guidelines are just that, guides, and shall be considered if they make sense in the particular context.

In this case, being that the data is moved to the bin, after pressing a very specific key, the likelyhood of data loss is near to nil.

**Comment by es20490446e** [comment]
On the other hand having that dialogue, if you try it, is quite obstructive while having to look over photos while deciding which to delete.

Each time you press "supr" you are presented with it, and if you tick the option "don' show this dialogue again on this session", you basically cannot exit the app while doing so is important when having tons of photos, to jump on the file manager right to the appropriate one versus having to visit each of them one by one in eom.
