### ISSUE TITLE
colour prints are inaccurate (brown is purple, orange is red)

### ISSUE THREAD

**Issue by linuxgirl22** [mate-desktop/eom#243]
Hello :-)
Sorry if this is the wrong section; I looked through a lot of the others, and could only find reference to printing in this one. 

I'm using the same method/driver/hardware as when printer was previously working, but very different output ... eg brown is purple, orange is red, test sheet is overall purple/blue/reddish. When I go to print artwork, there is no colour profile available.

Epson WF-2630
Local/usb serial
Using mate desktop, latest version, all latest updates.
All cartridges recently installed and at least half full ... magenta lowest, at half; then cyan, then yellow, and black is full. 

Installed the same AUR driver (epson-inkjet-printer-escpr) [beginner to Arch, and only very recently to Mate]. 
I've tried printing from gthumb instead of eye of mate, and also tried directly printing a testpage from localhost as well as directly from desktop print settings. 
I've tried removing the printer, rebooting ... it auto-installed itself, with the same issues. 
I've tried choosing a different driver via localhost. 

Nothing is making any difference, so I can only comprehend that it's something to do with Mate?

**Comment by lukefromdc** [comment]
If the images display properly on the screen, it's very unlikely this comes from EOM. Might be the ink itself in your printer as old/dried/low ink can most certainly cause wrong or changed colors.
Try new ink first, if you don't need EXACT colors you might want to go with 3ed party ink so as not to reward corrupt "razor and blade" printer marketing practices that sell ink for the price of human blood.

**Comment by lukefromdc** [comment]
OK, same issue when on KDE proves MATE isn't the problem, as is the fact that cleaning the printer has any effect. We can close this here, worst case for you might be a new print head if your printer uses a printhead separate from the ink cartridges, which can get clogged in some cases with old ink. The one good thing about the combined cartridge/print head system is a new print head when you change ink.

**Comment by linuxgirl22** [comment]
I've ordered a new, ecotank, printer, as a whole set of cartridges was wasted yesterday, with all the tests/cleaning etc. Hopefully there won't be lots of image editing etc before getting an accurate printout with the new one, but of course that's me referencing printing on linux overall. Mate is awesome, so it's great to know it's not a Mate issue.
