### ISSUE TITLE
Ability o rename file within opened EOM

### ISSUE THREAD

**Issue by Ygarr** [mate-desktop/eom#255]
#### Expected behaviour
Open image and desire to rename it pressinng f2 or via menu - no such option

#### Actual behaviour
Do nothing. Need to seek this file in File Manager to rename

#### Steps to reproduce the behaviour
Open image, search how to rename file

#### MATE general version
Last

#### Package version
1.22.2-1

#### Linux Distribution
Manjaro

**Comment by mbkma** [comment]
see #115

**Comment by Ygarr** [comment]
Ok, 
1. compromise solution 
2. after renaming file I got two file: one with wrong name and second with corrected name(w/o knowing about changing it`s quality)
3. I cannot reach wrong named file in collection of images in current EOM session after full going through
4.Ctr+Shift+S does not solve the problem of working with information, with large amount of image files and make hard to sort them

**Comment by mbkma** [comment]
No, I actually agree with you that renaming files from running eom would be a nice feature. This issue is just a duplicate of #115, that is why I closed this issue here.
