### ISSUE TITLE
[Compile-related problem] eom fails to compile in libeom.a with hidden symbol `eom_metadata_reader_get_icc_profile' isn't defined

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/eom#258]
I am trying to compile eom version 1.24.0 from source.

The result is:

/usr/bin/ld: ./.libs/libeom.a(libeom_la-eom-image.o): in function `eom_image_load':
eom-image.c:(.text+0x1a09): undefined reference to `eom_metadata_reader_get_icc_profile'
/usr/bin/ld: eom: hidden symbol `eom_metadata_reader_get_icc_profile' isn't defined
/usr/bin/ld: final link failed: bad value

I am not sure what icc_profile is.

Evidently something did not work in the function eom_imag_load but I am not sure what it was.

If it is not too much work, could perhaps the component(s) required for this be checked through the configure script? I assume something on my system is not working right now, but I was able to compile eom before, so this is most likely an user error (from me), but also a lack of information shown by eom as to what the problem is. At any rate I just report this - feel free to close it if it is not a useful report or too much work. Thanks!

**Comment by lukefromdc** [comment]
I just had a successful build on Debian Unstable, no problems here

**Comment by egnappahz** [comment]
...yeah, so, you need "libexif", which isnt checked by autogen. Installing that library will let the build succeed. Good luck.

**Comment by NP-Hardass** [comment]
I've reproduced this linkage failure when built with ./configure --without-exif --with-cms

**Comment by NP-Hardass** [comment]
OK, I found the source... be4fa2808c4e1a36c2c9b58c1267a54cdda6e495 added a bunch of "defined(GDK_WINDOWING_X11)" which only work if there are accompanying #include <gdk/gdk.h>

**Comment by NP-Hardass** [comment]
I'm not sure what the best way to address it is... You want a gdk import in every file that now has the GDK_WINDOWING_X11?
