### ISSUE TITLE
Problem with the documentation of eom

### ISSUE THREAD

**Issue by JerareYoshi** [mate-desktop/eom#262]
In the "Getting Started" chapter and in the "Image Collection" section it tells than the shortcut is F9 but in eom the shortcut is actually Ctrl + F9 .

**Comment by JerareYoshi** [comment]
I just saw it also affect other parts of the eom documentation.

In Getting Started "Image Information Pane" (called Side Panel in eom) the shortcut should be F9 and not Ctrl + I.

Same errors appear in the Viewing Images chapter because they use the same shortcuts and Ctrl + W can't "return to the normal view" because it will close eom.

**Comment by rbuj** [comment]
PR https://github.com/mate-desktop/eom/pull/265
