### ISSUE TITLE
Cannot build version 1.20.0

### ISSUE THREAD

**Issue by x0red** [mate-desktop/eom#292]
#### Expected behaviour
Successful build on machine with currently working version 1.20.0 of eom.

#### Actual behaviour
From the log of the build (./autogen.sh --prefix=/usr --sysconfdir=/etc):
configure: error: Package requirements (gtk+-3.0 >= 3.22.0              glib-2.0 >= 2.50.0              gmodule-2.0              gio-2.0 >= 2.50.0              gio-unix-2.0 >= 2.50.0              gthread-2.0 >= 2.50.0              mate-desktop-2.0 >= 1.17.0              gdk-pixbuf-2.0 >= 2.30.0              gio-2.0 >= 2.50.0              gtk+-unix-print-3.0 >= 3.22.0              shared-mime-info >= 0.20              libpeas-1.0 >= 1.2.0              libpeas-gtk-1.0 >= 1.2.0 libexif >= 0.6.14) were not met:

**No package 'mate-desktop-2.0' found**

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables EOM_CFLAGS
and EOM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

#### Steps to reproduce the behaviour
Suppose you on the host with MATE 1.20.1, Release 18.04.5 LTS (Bionic Beaver) 64-bit
`git checkout v1.20.0`
`aptitude install mate-common yelp-tools gobject-introspection libpeas-dev`
#### MATE general version
`aptitude show mate-desktop`
> Version: 1.20.1-2ubuntu1

#### Package version
1.20.0??

#### Linux Distribution
Mate, Release 18.04.5 LTS (Bionic Beaver) 64-bit

#### Link to bugreport of your Distribution (requirement)
https://github.com/mate-desktop/eom/issues/new

**Comment by lukefromdc** [comment]
This has nothing to do with the source packages here. I install from locally builds of all of MATE, that would surely work for you as well, once you manually work through all the dependencies. 

Most likely you didn't get the -dev package offered by Ubuntu for mate-desktop, install that, and look for such packages for all dependencies that are coming back unsatisfied. If Ubuntu isn't offering them, that's a distro problem that needs to be fixed on their end. We can do nothing here about such issues.

**Comment by x0red** [comment]
I have to say that you were right :) Thank you so much! it was just confusing 'mate-desktop-2.0' while I has 'mate 1.20'
