### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Catwowo** [mate-desktop/eom#338]
when i  have been installed gobject-introspection1.0 , also have this problem ,how should i do ?
./connfigure: line 17713: syntax error near unexpected token `0.9.3'
./configure: line 17713: `GOBJECT_INTROSPECTION_CHECK(0.9.3)'

**Comment by stephenboston** [comment]
Me too. I found this ancient post https://bugs.freedesktop.org/show_bug.cgi?id=35261 that looks promising but aclocal_flags is not defined anywhere in the eom installation code.

**Comment by mbkma** [comment]
You can see all packages needed for building eom here: https://github.com/mate-desktop/eom/blob/master/.build.yml

**Comment by mbkma** [comment]
Also you should inform about your system, distribution, version-numbers and print full error message here in order to get help.

**Comment by stephenboston** [comment]
Thank you your response. 

I'm on Arch up to date with kernel 6.01, all deps listed in your link are installed .

I _have_ managed to build and install though. I did this:

$ NOCONFIGURE=1 ./autogen.sh

This **failed** after warnings (see below) . 

I then tried to make anyway (no go) 

so I then ran 

```
$ ./configure
$. make
$ sudo make install.

```
All without error and 
And hey presto. 

Here's the warnings from autogen


> > NOCONFIGURE=1 ./autogen.sh
/usr/bin/mate-autogen
/usr/bin/yelp-build
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.71
configure.ac:36: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:36: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:36: the top level
configure.ac:56: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:56: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:56: the top level
configure.ac:215: warning: The macro `AC_TRY_CPP' is obsolete.
configure.ac:215: You should run autoupdate.
./lib/autoconf/general.m4:2762: AC_TRY_CPP is expanded from...
configure.ac:215: the top level
configure.ac:284: warning: The macro `AC_WARN' is obsolete.
configure.ac:284: You should run autoupdate.
./lib/autoconf/oldnames.m4:33: AC_WARN is expanded from...
configure.ac:284: the top level
checking for pkg-config >= 0.14.0...
  testing pkg-config... found 1.8.0
checking for gtk-doc >= 1.0...
  testing gtkdocize... grep: warning: stray \ before ,
grep: warning: stray \ before white space
found 1.33.1
Checking for required M4 macros...
Checking for forbidden M4 macros...
Processing ./configure.ac
configure.ac:36: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:36: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:36: the top level
configure.ac:56: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:56: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:56: the top level
configure.ac:215: warning: The macro `AC_TRY_CPP' is obsolete.
configure.ac:215: You should run autoupdate.
./lib/autoconf/general.m4:2762: AC_TRY_CPP is expanded from...
configure.ac:215: the top level
configure.ac:284: warning: The macro `AC_WARN' is obsolete.
configure.ac:284: You should run autoupdate.
./lib/autoconf/oldnames.m4:33: AC_WARN is expanded from...
configure.ac:284: the top level
Running gtkdocize...
grep: warning: stray \ before ,
grep: warning: stray \ before white space
Running autoreconf...
autoreconf: export WARNINGS=no-portability
autoreconf: Entering directory '.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: running: gtkdocize --copy
grep: warning: stray \ before ,
grep: warning: stray \ before white space
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: running: /usr/bin/autoconf --force
configure.ac:36: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:36: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:36: the top level
configure.ac:56: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:56: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:56: the top level
configure.ac:215: warning: The macro `AC_TRY_CPP' is obsolete.
configure.ac:215: You should run autoupdate.
./lib/autoconf/general.m4:2762: AC_TRY_CPP is expanded from...
configure.ac:215: the top level
configure.ac:284: warning: The macro `AC_WARN' is obsolete.
configure.ac:284: You should run autoupdate.
./lib/autoconf/oldnames.m4:33: AC_WARN is expanded from...
configure.ac:284: the top level
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:31: installing './compile'
configure.ac:10: installing './missing'
cut-n-paste/toolbar-editor/Makefile.am: installing './depcomp'
autoreconf: Leaving directory '.'
Skipping configure process.

**Comment by stephenboston** [comment]
I'm looking for a full screen and zoom without scrollbars. There's no option in preferences. 

In` eom-scrollI-view.c` I  see `check_scrollbar_visibility`. As a first go, I tried putting `hbar_visible = vbar_visible = FALSE;` at line 50, but this didn't work.

**Comment by lukefromdc** [comment]
I think the key to this is "skipping configuration process" or wharever it was (away from my desktop at the moment). NO idea what causes it but that I would expect to mean no makefiles and thus no build.

**Comment by Catwowo** [comment]
thanks!
my problem is soluted :
(here are my adjustment)
1.build:delete command './configure'
2.setup:add dependencies: gobject-introspection dconf gdk-pixbuf2 gtk3
