### ISSUE TITLE
eom -> libpeas ->gjs : can dependencies be reduced?

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/eom#352]
Hey folks,

First, I compile most everything from source on my linux machine here.

I also compiled the latest stable of mate desktop, at the least the majority of the components.

Here is a copy/paste output from a commandline ruby script that tells me which versions are installed on the local computer (and another script tracks releases of new versions of mate etc...):

    Mate-Desktop:             1.28.2
    Mate-Utils:               1.28.0
    Mate-Applets:             1.28.0
    Mate-Common:              1.28.0
    Mate-Control-Center:      1.28.0
    Mate-Keyboard:            1.28.0
    Mate-Media:               1.28.0
    Mate-Mixer:               1.28.0
    Mate-Notification Daemon: 1.28.1
    Mate-Weather:             1.28.0
    Mate-Panel:               1.28.4
    Mate-Power-Manager:       1.28.0
    Marco:                    1.28.1
    Mate-Screensaver:         1.28.0
    Atril:                    1.28.0
    Eom:                      sh: line 1: eom: command not found
    Pluma:                    sh: line 1: pluma: command not found
    Engrampa:                 1.28.2
    Caja:                     1.28.0
    Caja-extensions:          1.28.0

So I have most things; eom and pluma not yet.

The latter two both require libpeas.

I check on the libpeas source tarball here:

https://download.gnome.org/sources/libpeas/?C=M;O=D

Latest stable is 2.0.5.

It requires gjs.

https://www.linuxfromscratch.org/blfs/view/svn/gnome/gjs.html

I have some problems compiling gjs. Now, that can be solved I suppose,
but I am doing this primarily to get eom and pluma to work.

My question is: are these dependency chains really necessary? Is javascript
via gjs really required for eom and pluma? At the least for eom, where an
image is shown (image viewer) as a primary function, it strikes me as strange
that we need javascript. Could this be made into an optional dependency 
perhaps, and the check changed to "if gjs is not installed, notify the user,
but continue to compile / configure it"?

I don't know the source well to understand whether javascript is required, but
if it could be made optional that would be nice - it would have more flexibility.

(eom and pluma are not critical, so I can skip them anyway, but I also kind of
want a "complete" mate-desktop as much as possible. That would also mean 
I get gjs installed eventually, of course, but often when I compile mate-desktop
I bootstrap on a fresh computer, and then my mindset is more that I want 
mate-desktop quickly up-and-running and let it run for days to come. In that
context it would be nice if eom and pluma would also work just fine.)

**Comment by cwendling** [comment]
MATE doesn't make libpeas, so we don't control how it manages its dependencies.
However, libpeas is library that facilitate loading plugins, and especially plugins written in various languages (including Python and JavaScript).  It probably could work just fine without the ability to load JS though.

This said, I just peeked at the source code, and it really seem to make it easy to disable through a build option, see https://gitlab.gnome.org/GNOME/libpeas/-/blob/main/meson.build?ref_type=heads#L123 and https://gitlab.gnome.org/GNOME/libpeas/-/blob/main/meson_options.txt  It looks like you just have to set the `gjs` option and you're good: `meson configure -Dgjs=false` or something like that.
