### ISSUE TITLE
Gtk+3: list of things to be fixed

### ISSUE THREAD

**Issue by infirit** [mate-desktop/eom#55]
I went through eog git and got Gtlk+3 eom working except a few little things like the below. I could not a commit for these so documenting them here.

 * Segfault when adding items to the toolbar
 * Sefgault when enabling "image collection"
 * Toolbar editor scroll window needs an expand property set somewhere. // Fixed

Otherwise it runs quite nicely now under Gtk3. Thanks to eog devs for the commits :smile:

**Comment by NiceandGently** [comment]
https://github.com/mate-desktop/eom/pull/80

**Comment by NiceandGently** [comment]
https://github.com/mate-desktop/eom/pull/81

**Comment by flexiondotorg** [comment]
Pull requests #80 and #81 have been merged.
