### ISSUE TITLE
CR2 Format Support

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/eom#58]
Eye of MATE supporting the .CR2 format image file would be great. Would it be possible to add this feature in the next release? 
##

**Comment by monsta** [comment]
Interesting, [here](https://mail.gnome.org/archives/eog-list/2016-January/msg00001.html) and [here](https://bugs.launchpad.net/bugs/967471) Felix Riemann said that RAW files (and CR2 are among these) are auto-supported by eog if a gdk-pixbuf loader from libopenraw is installed. No eog code modification is required. It might be the same for eom... so does your distro ship a gdk-pixbuf loader from libopenraw?

**Comment by flexiondotorg** [comment]
No feedback.
