### ISSUE TITLE
Plugin "Date in Statusbar" does not put date into statusbar and conflicts with "Automatic orientation"

### ISSUE THREAD

**Issue by woox2k** [mate-desktop/eom#63]
Title is pretty much self explanatory. Also this plugin seems to conflict with "Automatic Orientation" option. If both are enabled then eom often (not always) fails to open an image entirely.

Steps to reproduce:
1. Enable "Date in Statusbar" plugin
2. Open an image and look at the status bar.
3. Enable Automatic orientation
4. Open image file again
5. If it opens nicely then close it and go to step 4, try again until it gets stuck at "Loading image..."

![ss-20141130-1ydkn](https://cloud.githubusercontent.com/assets/5333424/5237568/002f12f6-7896-11e4-886e-db21ebadb750.png)

OS info:
Archlinux x64
eom version 1.8.1-1

**Comment by monsta** [comment]
I was able to reproduce only a half of this issue (date not shown). I'm using eom built from git master (1.9.x) though, not 1.8.x.
Try https://github.com/mate-desktop/eom/pull/67 and see if it fixes the problem.

**Comment by monsta** [comment]
So, half of this had been fixed and another half isn't reproducible here. If no one reproduces it with eom 1.12, I'll consider this fixed.
