### ISSUE TITLE
please add real auto-refresh (rather than auto-do-you-want-to-refresh)

### ISSUE THREAD

**Issue by FurcyPin** [mate-desktop/eom#69]
Hi,

When using eom to visualise the image output of a program that I re-run quite often,
I would like eom to automatically refresh that image when it has changed (even when not given focus)
rather than proposing me to click or hit alt-R every time.

If other people prefer the current behaviour, adding a switch button in the preferences would be good enough. Although I think auto-refresh is now the current default behavior in eog.

**Comment by eosrei** [comment]
+1. I just installed eog and that has solved this issue for me. I'd rather use eom though.

**Comment by monsta** [comment]
Fixed. Now it will be the same as in eog: if you didn't modify (e.g. rotate) the image via eom itself, it will auto-reload on the file change without asking.
