### ISSUE TITLE
sidebar is always disabled and there's no way to enable it

### ISSUE THREAD

**Issue by monsta** [mate-desktop/eom#74]
- `View -> Side Pane` menu item is always greyed out, its shortcut (Ctrl-F9) is disabled;
- if I enable `sidebar` key in `org.mate.eom.ui` schema, eom disables it on the next run;
- there are functions to add/remove sidebar "pages" (wtf is that?) in `eom-sidebar.c` - but they're never ever ever called anywhere.

Tested in eom 1.8 and 1.10.

Eye of Gnome has that functionality enabled but there are no relevant commits that we could cherry-pick.
##

**Comment by NiceandGently** [comment]
I found those interesstings discussions about eog sidebar.
https://bugzilla.gnome.org/show_bug.cgi?id=668178
https://bugzilla.gnome.org/show_bug.cgi?id=616438
I digged in a bit deeper today, and it looks like that this was never a prob with eog.
But:
- i can enable the sidebar with dconf-editor
- i leave dconf-editor open
- just in the moment eom starts , you see tat the key changed in dconf-editor to 'false'

So, i quess that we have a gsettings issue which was introduced during gsettings port in 1.6.

**Comment by bl0ckeduser** [comment]
The code has been removed from eom at some point, in eog it is in src/eog-metadata-sidebar.c. Not sure why

**Comment by monsta** [comment]
Weird... there's no such file in the initial commit here...

**Comment by monsta** [comment]
Ah wait, it really wasn't there in eog 2.32. It has been introduced before 3.0 release I think. See [the log](https://git.gnome.org/browse/eog/log/src/eog-metadata-sidebar.c).

**Comment by monsta** [comment]
Ok, now I know why sidebar is disabled - there were no plugins that used it. After I made a test plugin that uses it (https://github.com/mate-desktop/eom/issues/71#issuecomment-268219665), it started to work.

**Comment by monsta** [comment]
We can also pick the mentioned upstream code for showing the image metadata in the sidebar. That would allow enabling/disabling sidebar at any time (provided that some image is loaded), without any additional plugins. But I don't think it's so urgent.

**Comment by raveit65** [comment]
fixed with https://github.com/mate-desktop/eom/commit/b1c0911213e74d91059aaa8442898e52e13368af
