### ISSUE TITLE
Wrong translations for eom gsettings keys

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/eom#82]
Eom's gsettings keys are wrong translated with 1.10.
![dconf-editor](https://cloud.githubusercontent.com/assets/961604/8155542/8dcb4c20-1345-11e5-88f8-3c7fcd31f4d1.png)

**Comment by clefebvre** [comment]
Confirmed. Observed in Mint as well with any language.

**Comment by NiceandGently** [comment]
confirmed, i t fixes the issue in fedora

**Comment by NiceandGently** [comment]
So, same needs to be done for pluma and mate-utils. atril, mate-system-monitor if this list is correct.
https://github.com/mate-desktop/debian-packages/issues

**Comment by monsta** [comment]
m-s-m has different issue it seems - C++ linker is angry about missing libs (though they should be found normally)... go figure :-/

**Comment by flexiondotorg** [comment]
Pull request #83 is now merged which fixed this issue.
