### ISSUE TITLE
Fails to scroll after Zoom-In(+) in Full-Screen

### ISSUE THREAD

**Issue by ShianLee** [mate-desktop/eom#91]
After installing Linux Mint 17.2 MATE ("Rafaela"), I view JPG images in full-screen (F11), then Zoom-In (+), then it's impossible to scroll the images normally. 
This issue do not appear in 'Eye of GNOME' on the same installation of Linux Mint - only appears with 'Eye of MATE'.

**Comment by monsta** [comment]
already fixed in 1.10.3 (https://github.com/mate-desktop/eom/commit/63eee4d641692a07f41bce3b7fd21668d8fe2f1e)
@infirit: please close this
