### ISSUE TITLE
error compile eom to gcc-4.9.3

### ISSUE THREAD

**Issue by pantera31752** [mate-desktop/eom#94]
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../lib64/libcairo.so: undefined reference to symbol 'XUnlockDisplay'
/usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:751: recipe for target 'eom' failed
make[3]: *** [eom] Error 1
make[3]: Leaving directory '/var/calculate/tmp/portage/media-gfx/eom-1.10.0/work/eom-1.10.0/src'
Makefile:652: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/var/calculate/tmp/portage/media-gfx/eom-1.10.0/work/eom-1.10.0/src'
Makefile:534: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/calculate/tmp/portage/media-gfx/eom-1.10.0/work/eom-1.10.0'
Makefile:465: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pantera31752** [comment]
I'm sorry to trouble you, fixing

**Comment by infirit** [comment]
Looks like a cairo is missing a link to -lX11. However this is outside of eom's control as it get's it's linker flags from the cairo pkg-config file.

**Comment by pantera31752** [comment]
Yes, Thanks

**Comment by oleid** [comment]
I just stumbled across the same problem when building eom-1.12 on gentoo/arm. As far as I can tell, cairo.pc shouldn't  include X11 libs, as cairo works very well without X11 deps. Thus, if one requires cairo's X11 backends, one should use one of

    hemera # pkg-config --libs cairo-xlib
    -lcairo -lX11 -lXext 
    hemera # pkg-config --libs cairo-xcb
    -lcairo -lxcb-render -lxcb 

in the configure script.
