### ISSUE TITLE
Cannot configure with libexif from pkg-config

### ISSUE THREAD

**Issue by brunodefraine** [mate-desktop/eom#95]
I cannot configure eom with libexif in a non-builtin location (a prefix other than /usr), even though it is correctly found by pkg-config.

From eom's configure.ac:

```
AC_ARG_WITH([libexif], AC_HELP_STRING([--without-libexif], [disable EXIF support]))
have_exif=no
if test x$with_libexif != xno; then
    PKG_CHECK_MODULES(EXIF, libexif >= $LIBEXIF_REQUIRED, have_exif=yes, have_exif=no)
    if test "x$have_exif" = "xyes"; then
        AC_CHECK_HEADER([libexif/exif-data.h],[],[have_exif=no])
    fi
fi
if test "x$have_exif" = "xyes"; then
  AC_DEFINE(HAVE_EXIF, 1, [EXIF Support.])
  EOM_MODULES="$EOM_MODULES libexif >= $LIBEXIF_REQUIRED"
fi
```

The problem is with the ``AC_CHECK_HEADER``; this will try to find the ``exif-data.h`` header, but it does *not* employ the necessary "cflags" returned by pkg-config. So in my case, it will fail to find the header, even though it is available. If I disable the ``AC_CHECK_HEADER``, I can correctly compile eom.

**Comment by infirit** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=465628 :sob:

I'll remove this header check because we should be able to assume when pkg-config succeeds we should be able to assume the headers are there.
