### ISSUE TITLE
No resampling on zoom

### ISSUE THREAD

**Issue by scytho** [mate-desktop/eom#96]
Since the upgrade from Mint 17.1 to 17.2., images are simply resized on zoom, not resampled. That issue already occurred some years ago (with eog on Ubuntu, I think).
##

**Comment by infirit** [comment]
images is very broad, what type of image? My guess is svg, if so see https://github.com/mate-desktop/eom/issues/52 and report it to your distro.

**Comment by scytho** [comment]
JPG, TIFF and PNG, at least.

**Comment by infirit** [comment]
I see no such problems so more info will be required of how it was before and how it is now. Before and after screenshots will be helpful, example image and steps to reproduce.

**Comment by scytho** [comment]
If I download [this photograph](https://commons.wikimedia.org/wiki/File:Refugio_Militar_Capitan_Cobo_-_Pico_Veleta_-_Sierra_Nevada_-_2014-08-07.jpg) and open it in eom (v. 1.10.0 in Linux Mint 17.2), I see strong aliasing patterns in lines that are not oriented horizontally or vertically, like the lower parts of the antennas on the roof. There are jaggies on sloping edges or lines. Not so, when viewed in Firefox or Gimp.

I think, it is independent of the file. It is like IrfanView when not set on »resample for zoom«. It zooms more quickly, but ugly.

**Comment by infirit** [comment]
Not seeing any of that. I am not sure what changed in Mint between 17.1 and 17.2 that may cause this. Here is what I get on maximum zoom.
![eom_zoom](https://cloud.githubusercontent.com/assets/3465730/9154154/f8415f14-3e82-11e5-930f-39087608b1e3.png)

**Comment by infirit** [comment]
There is an option in gsettings which may be causing this. Open dconf-editor and go to ``/org/mate/eom/view`` and look for the ``interpolate`` and ``extrapolate`` options and see if these are enabled.

**Comment by scytho** [comment]
Interpolate and extrapolate are activated.

I forgot to mention, that the effect occurs when zooming out (to less than 100%), i.e. when viewing pictures that are large than the screen.

**Comment by scytho** [comment]
Next try to attach images:

![refugio_eom_after](https://cloud.githubusercontent.com/assets/13711754/9154676/1ab52ef8-3e9d-11e5-8d04-4ab189699ac6.png)
![refugio_iv](https://cloud.githubusercontent.com/assets/13711754/9154677/1ab7b290-3e9d-11e5-845c-2f984d67c2e5.png)

The first one is from eom. Notice the tiny black spot next to the right edge of the screenshot. That’s one of those little pointy things on the roof you can see in the original picture when zooming in. eom renders it as a black pixel. The second screen shot is from IrfanView (Wine). IrfanView renders that detail diffenrently. That’s with all fine details.

I couldn’t find a better example, so I made one:

![test](https://cloud.githubusercontent.com/assets/13711754/9154774/4532ba44-3ea0-11e5-98d6-c329f3a8853d.png)

Here’s a comparison of that image viewed in GIMP, IrfanView and eom at roughly the same zoom level:

![test3](https://cloud.githubusercontent.com/assets/13711754/9154779/5c9f7a28-3ea0-11e5-8ffa-9d5db0be6d9d.png)

**Comment by LavirtheWhiolet** [comment]
I confirm.

I've got some picture and resized it in eom to 10%. The following is what I got in different versions.

eom 1.8.0:
![1 8 0](https://cloud.githubusercontent.com/assets/231566/14491844/0bde2970-019d-11e6-88d9-01eeaf79b13e.png)

eom 1.12.0:
![1 12 0](https://cloud.githubusercontent.com/assets/231566/14491847/1442b144-019d-11e6-9400-7fdd1a7dd065.png)

Preferences in both:
![preferences](https://cloud.githubusercontent.com/assets/231566/14491883/41e6f9de-019d-11e6-9861-0895a331ca30.png)

**Comment by scytho** [comment]
Still the same in EOM 1.12.2. The bug occurs with all zoom levels other than 100%. It gets extrem at levels around 10% and lower, but you can see it at levels above 100%, too.

As I said, the bug isn’t new. There’s a couple of old versions that have that bug. It then disappeared for some years, now it’s back.

**Comment by LaurentBonnaud** [comment]
I also see this problem in Ubuntu 16.10 and EOM 1.16.0-1.
EOG does not have the same problem.

**Comment by wyatt8740** [comment]
EOG bug report appears to be [here](https://bugzilla.gnome.org/show_bug.cgi?id=665897) (bug 665897).

**Comment by scytho** [comment]
I’m not seeing this problem any more. I’m using Xviewer 1.6.1 (Mint 18.3, MATE 1.18.0). I hope it stays that way …

**Comment by raveit65** [comment]
Guys could you please test https://github.com/mate-desktop/eom/pull/175   ?
