### ISSUE TITLE
Vertical scroll bar problem with zoom

### ISSUE THREAD

**Issue by CountryBumkin** [mate-desktop/eom#98]
I am using Linux Mint 17.2 64 bit mate version and EOM seems to have a problem with vertical scroll. The issue can be repeated by doing this...

(1) Open any image with the height greater than the width.
(2) Move the sides of the window out so the window width is more than the height or maximize the window.
(3) Zoom in till a vertical scroll bar appears, it will be inoperable and the slider button will be small at the top.
(4) Keep zooming in till a horizontal scroll bar appears, at that moment the vertical scroll slider will change shape and the vertical scroll bar will commence to operate almost normally - it has an incorrect vertical size and will let you scroll down past the bottom of the image, the space is filled with repeats of the last row of pixels from the image..
(5) Zoom back out till the horizontal scroll disappears and the vertical scroll will keep working.
(6) Use the 'Next ' or 'Previous' buttons to select another image and the vertical scroll will keep working.
(7) You need to close and re-open the program to repeat the bug.

regards CB

**Comment by CountryBumkin** [comment]
There is some more discussion of the problem here...
http://forums.linuxmint.com/viewtopic.php?t=202691&p=1053840

**Comment by monsta** [comment]
That's fixed in 1.10.3 (https://github.com/mate-desktop/eom/commit/63eee4d641692a07f41bce3b7fd21668d8fe2f1e). Ask Clem to update eom in Mint :smile:
